### ISSUE TITLE
Display of vanilla recipes in the lexicon with the presence of MythicBotany.

### ISSUE THREAD

**Issue by Kastik404** [YerovaArusu/botanicpledge#22]
**Describe the bug**
In the lexicon, with MythicBotany, crafts are not replaced.
**Screenshots**
![изображение](https://github.com/user-attachments/assets/c9dba44b-a205-4c69-87d6-42cbeb8e1a9d)
![изображение](https://github.com/user-attachments/assets/dd88b8c6-7168-4730-b985-770121670745)
**Affected version**
Mod version 0.7.4.1
Forge version 47.3.11
Minecraft version 1.20.1
**Environment:**
MythicBotany
**Additional context**
I also want to say that I could not find a way to get the heart of yggdrasil.

**Comment by YerovaArusu** [comment]
Yes. Currently I don't know how to change the recipes in the book depending if MythicBotany is present or not.

And regarding the Heart of Yggdrasil:
It drops when fighting the Yggdrasil Guardian... But only with a 3.33% chance (I am considering to increase this drop chance to 15%)

I currently can't work much on this mod since I currently have a lot of exams and such. Because of that it might take longer than usual for me to publish a bug fix update.

**Comment by YerovaArusu** [comment]
well... it might be in the middle of classes for me but i found some time to fix the problems you mentioned.
New drop chance for the Yggdrasil Heart is now 15% and the recipes are now properly displayed
